name: Postman API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run Postman Collection
        run: |
          postman collection run "postman/PetStore.postman_collection.json" \
            --environment "postman/PetStore.postman_environment.json" \
            --working-dir "postman" \
            --reporters cli,html,junit \
            --reporter-html-export reports/postman-report.html \
            --reporter-junit-export reports/postman-report.xml

      - name: Upload test reports
        uses: actions/upload-artifact@v5
        with:
          name: postman-test-reports
          path: postman/reports/
 